### ISSUE TITLE
[4.x] Sending Statistics

### ISSUE THREAD

**Issue by tjrgg** [sylkellc/typicalbot#40]
### Description

Currently, TypicalBot only sends statistics to various bot listing sites when the bot is added to a new guild. I'd like to open a discussion about improving this to ensure that accurate statistics are being sent to the bot listing sites.

Possible Solutions
- Call the `sendStatistics` method in the `guildDelete` event.
- Establish a regular interval to send statistics to the bot listing sites.

### Have You...?
- [x] I have checked for related issues.
- [x] I have checked the documentation to ensure my idea or suggestion doesn't already exist.

**Comment by Skillz4Killz** [comment]
I would highly recommend the second option: `Establish a regular interval to send statistics to the bot listing sites.`

Using `guildDelete` can have unwanted side effects in the case of an API outage. Discord handles this as if the bot has left and emits the guildDelete event for every server because of an outage. This would eventually lead to thousands of server being "deleted" when they are not and that would spam bot lists API's but worse it would show inaccurate data of TB being removed when it really was not.

A regular interval like once an hour to call the `sendStatistics` update is a much better solution in my opinion.
